<sizechange>:
    orientation:'vertical'
    padding:10
    spacing:10
    Button:
        text:'click 1'
        size_hint:None,None
        size: 100,100
        
    Button:
        text:'click 2'
        size_hint:None,None
        size: 200,200
    Button:
        text:'click 3'
        size_hint:None,None
        size: 300,300
    Button:
        text:'click 4'
    Button:
        text:'click 5'
    Button:
        text:'click 6'
